// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pb} from '../models';

export function IngestItem(arg1:number):Promise<string>;

export function Search(arg1:string):Promise<Array<pb.Item>>;
