// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IngestItem(arg1) {
  return window['go']['main']['App']['IngestItem'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}
